#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "wifi_wh_config.h"
#include "mac.h"
#include "sleep_api.h"

/*
 * set to 1 to enable 5G
 */
#define WIFI_BAND_SELECT_5G              0

/*
 * if WIFI_SELECT_CH_NUM is set to 0, then AP will select a channel automatically
 * otherwise, AP will use the channel specificed by WIFI_SELECT_CH_NUM
 */
#define WIFI_SELECT_CH_NUM                12

/*
 * Value: 15 ~ (TU)
 */
#define WIFI_BCN_INTERVAL                  28

#define WIFI_PAIRING_TIME_OUT_MS          (3 * 60 * 1000)

#ifdef CFG_WIFI_ENGINEERING_MODE
/*
 * Value: Enable : 1 / Disable : 0
 */
#define WIFI_ENGINEERING_MODE_ENABLE        0
/*
 * Value: 0 ~ 3
 */
#define WIFI_ENGINEERING_MODE_CH_INDEX     2
#endif

/*
 * Value: 1 ~ VOICE_MAX_STREAMS
 */
#define HEADSET_NUM                        1

/*
 * Value: POWER_MODE_LEVEL_T
 */
#define HEADSET_POWER_MODE                 PM_LEVEL_ACTIVE

/* USB audio config, do NOT modify them here */
#define USB_AUDIO_SAMPRATE                  48000
#define USB_AUDIO_SAMPBITS                  16
#define USB_AUDIO_CH_NUM                    2
#define USB_AUDIO_PKT_SIZE_MS               1
#define USB_AUDIO_PKT_SIZE                  (((USB_AUDIO_SAMPRATE + 999) / 1000) * USB_AUDIO_SAMPBITS / 8 * USB_AUDIO_CH_NUM * USB_AUDIO_PKT_SIZE_MS)

#define HEADSET_MIC_SAMPRATE                48000
#define HEADSET_CAPTURE_IN_CH_NUM           2
#define HEADSET_CAPTURE_OUT_CH_NUM          2

#define HEADSET_PLAYBACK_FRAME_SIZE_MS     (7)
#define HEADSET_CAPTURE_FRAME_SIZE_MS      (7)

#define HEADSET_PLAYBACK_FRAME_SIZE        (HEADSET_PLAYBACK_FRAME_SIZE_MS * ((USB_AUDIO_SAMPRATE + 999) / 1000) * USB_AUDIO_SAMPBITS / 8 * USB_AUDIO_CH_NUM)
#define HEADSET_CAPTURE_FRAME_SIZE         (HEADSET_CAPTURE_FRAME_SIZE_MS * HEADSET_MIC_SAMPRATE / 1000 * HEADSET_CAPTURE_IN_CH_NUM * sizeof(int16_t))

/* for 48K, 16bits, 2ch, 1ms is 192byte*/
#define D2H_AIR_PKT_SIZE_MS                 (7)
#define H2D_AIR_PKT_SIZE_MS                 (7)
#define D2H_AIR_PKT_SIZE                    (D2H_AIR_PKT_SIZE_MS * ((USB_AUDIO_SAMPRATE + 999) / 1000) * USB_AUDIO_SAMPBITS / 8 * USB_AUDIO_CH_NUM)
#define H2D_AIR_PKT_SIZE                    (H2D_AIR_PKT_SIZE_MS * HEADSET_MIC_SAMPRATE / 1000 * HEADSET_CAPTURE_OUT_CH_NUM * sizeof(int16_t))

#define USB_RX_RING_BUFFER_SIZE_MS          (10 * 7)
#define USB_TX_RING_BUFFER_SIZE_MS          (24 * 7)
#define USB_TX_START_LEVEL_SIZE_MS          (8 * 7)
#define USB_TX_AUTO_START_LEVEL_SIZE_MS     (16 * 7)
#define USB_RX_RING_BUFFER_SIZE             (USB_RX_RING_BUFFER_SIZE_MS * ((USB_AUDIO_SAMPRATE + 999) / 1000) * USB_AUDIO_SAMPBITS / 8 * USB_AUDIO_CH_NUM)
#define USB_TX_RING_BUFFER_SIZE             (USB_TX_RING_BUFFER_SIZE_MS * HEADSET_MIC_SAMPRATE / 1000 * HEADSET_CAPTURE_OUT_CH_NUM * sizeof(int16_t))
#define USB_TX_START_LEVEL_SIZE             (USB_TX_START_LEVEL_SIZE_MS * HEADSET_MIC_SAMPRATE / 1000 * HEADSET_CAPTURE_OUT_CH_NUM * sizeof(int16_t))
#define USB_TX_AUTO_START_LEVEL_SIZE        (USB_TX_AUTO_START_LEVEL_SIZE_MS * HEADSET_MIC_SAMPRATE / 1000 * HEADSET_CAPTURE_OUT_CH_NUM * sizeof(int16_t))

#define HEADSET_PLAYBACK_RING_BUFFER_SIZE_MS    (10 * 7)
#define HEADSET_CAPTURE_RING_BUFFER_SIZE_MS     (10 * 7)
#define HEADSET_PLAYBACK_START_LEVEL_SIZE_MS    (8 * 7)
#define HEADSET_PLAYBACK_RING_BUFFER_SIZE       (HEADSET_PLAYBACK_RING_BUFFER_SIZE_MS * ((USB_AUDIO_SAMPRATE + 999) / 1000) * USB_AUDIO_SAMPBITS / 8 * USB_AUDIO_CH_NUM)
#define HEADSET_CAPTURE_RING_BUFFER_SIZE        (HEADSET_CAPTURE_RING_BUFFER_SIZE_MS * HEADSET_MIC_SAMPRATE / 1000 * HEADSET_CAPTURE_OUT_CH_NUM * sizeof(int16_t))
#define HEADSET_PLAYBACK_START_LEVEL_SIZE       (HEADSET_PLAYBACK_START_LEVEL_SIZE_MS * ((USB_AUDIO_SAMPRATE + 999) / 1000) * USB_AUDIO_SAMPBITS / 8 * USB_AUDIO_CH_NUM)

#if (HEADSET_PLAYBACK_START_LEVEL_SIZE_MS > HEADSET_PLAYBACK_RING_BUFFER_SIZE_MS)
#error HEADSET_PLAYBACK_RING_BUFFER_SIZE_MS must be less than HEADSET_PLAYBACK_START_LEVEL_SIZE_MS
#endif

#if (HEADSET_PLAYBACK_RING_BUFFER_SIZE_MS < (2 * HEADSET_PLAYBACK_FRAME_SIZE_MS))
#error HEADSET_PLAYBACK_RING_BUFFER_SIZE_MS must be greater than (2 * HEADSET_PLAYBACK_FRAME_SIZE_MS)
#endif

#if (HEADSET_CAPTURE_RING_BUFFER_SIZE_MS < (2 * HEADSET_CAPTURE_FRAME_SIZE_MS))
#error HEADSET_CAPTURE_RING_BUFFER_SIZE_MS must be greater than (2 * HEADSET_CAPTURE_FRAME_SIZE_MS)
#endif

#if ((D2H_AIR_PKT_SIZE_MS > WIFI_BCN_INTERVAL) || (H2D_AIR_PKT_SIZE_MS > WIFI_BCN_INTERVAL))
#error D2H_AIR_PKT_SIZE_MS and H2D_AIR_PKT_SIZE_MS must be less than WIFI_BCN_INTERVAL
#endif

#define STA_CHECK_PERIOD_MS                 100

/*
 * if mac addr is all zeros, real mac addr will be generated by random number generator
 * if you want to specify mac addr, at least one byte should be none-zero
 */
static uint8_t dongle_mac_addr[6] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
static uint8_t headset_mac_addr[6] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

uint8_t wifi_wh_config_band_get(void)
{
    return (WIFI_BAND_SELECT_5G ? 1 : 0);
}
uint16_t wifi_wh_config_bcn_interval_get(void)
{
    return WIFI_BCN_INTERVAL;
}
uint32_t wifi_wh_config_pariring_timeout_get(void)
{
    return WIFI_PAIRING_TIME_OUT_MS;
}

#ifdef CFG_WIFI_ENGINEERING_MODE
bool wifi_wh_config_enable_em_chan_get(void)
{
    return WIFI_ENGINEERING_MODE_ENABLE;
}
uint8_t wifi_wh_config_em_chan_index_get(void)
{
    return WIFI_ENGINEERING_MODE_CH_INDEX;
}
#endif

uint8_t wifi_wh_config_headset_num_get(void)
{
    return HEADSET_NUM;
}

uint8_t wifi_wh_config_headset_pwr_mode_get(void)
{
    return HEADSET_POWER_MODE;
}

uint8_t wifi_wh_config_channel_get(void)
{
    return WIFI_SELECT_CH_NUM;
}

uint8_t *wifi_wh_config_dongle_mac_addr_get(void)
{
    if (MAC_ADDR_VALID(dongle_mac_addr)) {
        return &dongle_mac_addr[0];
    } else {
        return NULL;
    }
}

uint8_t *wifi_wh_config_headset_mac_addr_get(void)
{
    if (MAC_ADDR_VALID(headset_mac_addr)) {
        return &headset_mac_addr[0];
    } else {
        return NULL;
    }
}

uint16_t wifi_wh_config_usb_audio_pkt_size_get(void)
{
    return USB_AUDIO_PKT_SIZE;
}

uint16_t wifi_wh_config_headset_mic_samprate_get(void)
{
    return HEADSET_MIC_SAMPRATE;
}

uint8_t wifi_wh_config_headset_capture_in_ch_num_get(void)
{
    return HEADSET_CAPTURE_IN_CH_NUM;
}

uint8_t wifi_wh_config_headset_capture_out_ch_num_get(void)
{
    return HEADSET_CAPTURE_OUT_CH_NUM;
}

uint16_t wifi_wh_config_headset_playback_frame_size_ms_get(void)
{
    return HEADSET_PLAYBACK_FRAME_SIZE_MS;
}

uint16_t wifi_wh_config_headset_playback_frame_size_get(void)
{
    return HEADSET_PLAYBACK_FRAME_SIZE;
}

uint16_t wifi_wh_config_headset_capture_frame_size_ms_get(void)
{
    return HEADSET_CAPTURE_FRAME_SIZE_MS;
}

uint16_t wifi_wh_config_headset_capture_frame_size_get(void)
{
    return HEADSET_CAPTURE_FRAME_SIZE;
}

uint16_t wifi_wh_config_d2h_air_pkt_size_ms_get(void)
{
    return D2H_AIR_PKT_SIZE_MS;
}

uint16_t wifi_wh_config_h2d_air_pkt_size_ms_get(void)
{
    return H2D_AIR_PKT_SIZE_MS;
}

uint16_t wifi_wh_config_d2h_air_pkt_size_get(void)
{
    return D2H_AIR_PKT_SIZE;
}

uint16_t wifi_wh_config_h2d_air_pkt_size_get(void)
{
    return H2D_AIR_PKT_SIZE;
}

uint16_t wifi_wh_config_headset_playback_ring_buffer_size_ms_get(void)
{
    return HEADSET_PLAYBACK_RING_BUFFER_SIZE_MS;
}

uint16_t wifi_wh_config_headset_playback_start_level_size_ms_get(void)
{
    return HEADSET_PLAYBACK_START_LEVEL_SIZE_MS;
}

uint16_t wifi_wh_config_headset_capture_ring_buffer_size_ms_get(void)
{
    return HEADSET_CAPTURE_RING_BUFFER_SIZE_MS;
}

uint16_t wifi_wh_config_usb_rx_ring_buffer_size_ms_get(void)
{
    return USB_RX_RING_BUFFER_SIZE_MS;
}

uint16_t wifi_wh_config_usb_tx_ring_buffer_size_ms_get(void)
{
    return USB_TX_RING_BUFFER_SIZE_MS;
}

uint16_t wifi_wh_config_usb_tx_start_level_size_ms_get(void)
{
    return USB_TX_START_LEVEL_SIZE_MS;
}

uint32_t wifi_wh_config_headset_playback_ring_buffer_size_get(void)
{
    return HEADSET_PLAYBACK_RING_BUFFER_SIZE;
}

uint32_t wifi_wh_config_headset_playback_start_level_size_get(void)
{
    return HEADSET_PLAYBACK_START_LEVEL_SIZE;
}

uint32_t wifi_wh_config_headset_capture_ring_buffer_size_get(void)
{
    return HEADSET_CAPTURE_RING_BUFFER_SIZE;
}

uint32_t wifi_wh_config_usb_rx_ring_buffer_size_get(void)
{
    return USB_RX_RING_BUFFER_SIZE;
}

uint32_t wifi_wh_config_usb_tx_ring_buffer_size_get(void)
{
    return USB_TX_RING_BUFFER_SIZE;
}

uint32_t wifi_wh_config_usb_tx_start_level_size_get(void)
{
    return USB_TX_START_LEVEL_SIZE;
}

uint32_t wifi_wh_config_usb_tx_auto_start_level_size_get(void)
{
    return USB_TX_AUTO_START_LEVEL_SIZE;
}

uint32_t wifi_wh_config_sta_check_period_ms_get(void)
{
    return STA_CHECK_PERIOD_MS;
}

