#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "wifi_mic_config.h"
#include "mac.h"
#include "sleep_api.h"

/*
 * set to 1 to enable 5G
 */
#define WIFI_BAND_SELECT_5G               0

/*
 * if WIFI_SELECT_CH_NUM is set to 0, then AP will select a channel automatically
 * otherwise, AP will use the channel specificed by WIFI_SELECT_CH_NUM
 */
#define WIFI_SELECT_CH_NUM                14

#ifdef CFG_WIFI_ENGINEERING_MODE
/*
 * Value: Enable : 1 / Disable : 0
 */
#define WIFI_ENGINEERING_MODE_ENABLE        0
/*
 * Value: 0 ~ 3
 */
#define WIFI_ENGINEERING_MODE_CH_INDEX      2
#endif

/*
 * Value: 15 ~ (TU)
 */
#define WIFI_BCN_INTERVAL                  32


#define WIFI_PAIRING_TIME_OUT_MS          (3 * 60 * 1000)

/*
 * Value: 1 ~ VOICE_MAX_STREAMS
 */
#define MIC_TX_NUM                          1

/*
 * Value: POWER_MODE_LEVEL_T
 */
#define MIC_TX_POWER_MODE                   PM_LEVEL_HIBERNATE


#define MIC_SAMPRATE                        (16000)

#define TX2RX_AIR_PKT_SIZE_MS               (32)

#if (TX2RX_AIR_PKT_SIZE_MS > WIFI_BCN_INTERVAL)
#error TX2RX_AIR_PKT_SIZE_MS must small than WIFI_BCN_INTERVAL
#endif

#define TX_CAPTURE_IN_CH_NUM                (1)
#define TX_CAPTURE_OUT_CH_NUM               (1)
#define TX_PLAYBACK_CH_NUM                  (2)
#define RX_PLAYBACK_CH_NUM                  (2)

#define TX_CAPTURE_FRAME_SIZE_MS            (8)
#define TX_PLAYBACK_FRAME_SIZE_MS           (8)
#define RX_PLAYBACK_FRAME_SIZE_MS           (8)

#define TX2RX_AIR_PKT_SIZE                  (TX2RX_AIR_PKT_SIZE_MS * MIC_SAMPRATE / 1000 * TX_CAPTURE_OUT_CH_NUM * sizeof(int16_t))
#define TX_CAPTURE_FRAME_SIZE               (TX_CAPTURE_FRAME_SIZE_MS * MIC_SAMPRATE / 1000 * TX_CAPTURE_IN_CH_NUM * sizeof(int16_t))
#define TX_PLAYBACK_FRAME_SIZE              (TX_PLAYBACK_FRAME_SIZE_MS * MIC_SAMPRATE / 1000 * TX_PLAYBACK_CH_NUM * sizeof(int16_t))
#define RX_PLAYBACK_FRAME_SIZE              (RX_PLAYBACK_FRAME_SIZE_MS * MIC_SAMPRATE / 1000 * RX_PLAYBACK_CH_NUM * sizeof(int16_t))

#define TX_CAPTURE_RING_BUFFER_SIZE_MS      (TX_CAPTURE_FRAME_SIZE_MS * 10)
#define TX_PLAYBACK_RING_BUFFER_SIZE_MS     (TX_PLAYBACK_FRAME_SIZE_MS * 10)
#define RX_PLAYBACK_RING_BUFFER_SIZE_MS     (RX_PLAYBACK_FRAME_SIZE_MS * 10)
#define RX_PLAYBACK_START_LEVEL_SIZE_MS     (RX_PLAYBACK_FRAME_SIZE_MS * 4)

#if ((TX_CAPTURE_RING_BUFFER_SIZE_MS < (2 * TX_CAPTURE_FRAME_SIZE_MS)) || (TX_CAPTURE_RING_BUFFER_SIZE_MS < (2 * TX2RX_AIR_PKT_SIZE_MS)))
#error TX_CAPTURE_RING_BUFFER_SIZE_MS too small
#endif

#if ((TX_PLAYBACK_RING_BUFFER_SIZE_MS < (2 * TX_PLAYBACK_FRAME_SIZE_MS)) || (TX_PLAYBACK_RING_BUFFER_SIZE_MS < (2 * TX_CAPTURE_FRAME_SIZE_MS)))
#error TX_PLAYBACK_RING_BUFFER_SIZE_MS too small
#endif

#if ((RX_PLAYBACK_RING_BUFFER_SIZE_MS < (2 * RX_PLAYBACK_FRAME_SIZE_MS)) || (RX_PLAYBACK_RING_BUFFER_SIZE_MS < (2 * TX2RX_AIR_PKT_SIZE_MS)))
#error RX_PLAYBACK_RING_BUFFER_SIZE_MS too small
#endif

#define TX_CAPTURE_RING_BUFFER_SIZE         (TX_CAPTURE_RING_BUFFER_SIZE_MS * MIC_SAMPRATE / 1000 * TX_CAPTURE_OUT_CH_NUM * sizeof(int16_t))
#define TX_PLAYBACK_RING_BUFFER_SIZE        (TX_PLAYBACK_RING_BUFFER_SIZE_MS * MIC_SAMPRATE / 1000 * TX_CAPTURE_OUT_CH_NUM * sizeof(int16_t))
#define RX_PLAYBACK_RING_BUFFER_SIZE        (RX_PLAYBACK_RING_BUFFER_SIZE_MS * MIC_SAMPRATE / 1000 * TX_CAPTURE_OUT_CH_NUM * sizeof(int16_t))
#define RX_PLAYBACK_START_LEVEL_SIZE        (RX_PLAYBACK_START_LEVEL_SIZE_MS * MIC_SAMPRATE / 1000 * TX_CAPTURE_OUT_CH_NUM * sizeof(int16_t))

#define STA_CHECK_PERIOD_MS                 100

#if WIFI_BAND_SELECT_5G
static uint8_t band = 1;
#else
static uint8_t band = 0;
#endif

/*
 * if mac addr is all zeros, real mac addr will be generated by random number generator
 * if you want to specify mac addr, at least one byte should be none-zero
 */
static uint8_t rx_mac_addr[6] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
static uint8_t tx_mac_addr[6] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

uint8_t wifi_mic_config_band_get(void)
{
    return band;
}

uint16_t wifi_mic_config_bcn_interval_get(void)
{
    return WIFI_BCN_INTERVAL;
}

uint32_t wifi_mic_config_pariring_timeout_get(void)
{
    return WIFI_PAIRING_TIME_OUT_MS;
}

#ifdef CFG_WIFI_ENGINEERING_MODE
bool wifi_mic_config_enable_em_chan_get(void)
{
    return WIFI_ENGINEERING_MODE_ENABLE;
}
uint8_t wifi_mic_config_em_chan_index_get(void)
{
    return WIFI_ENGINEERING_MODE_CH_INDEX;
}
#endif

uint8_t wifi_mic_config_mic_tx_pwr_mode_get(void)
{
    return MIC_TX_POWER_MODE;
}

uint8_t wifi_mic_config_channel_get(void)
{
    return WIFI_SELECT_CH_NUM;
}

uint8_t *wifi_mic_config_mic_rx_mac_addr_get(void)
{
    if (MAC_ADDR_VALID(rx_mac_addr)) {
        return &rx_mac_addr[0];
    } else {
        return NULL;
    }
}

uint8_t *wifi_mic_config_mic_tx_mac_addr_get(void)
{
    if (MAC_ADDR_VALID(tx_mac_addr)) {
        return &tx_mac_addr[0];
    } else {
        return NULL;
    }
}

uint32_t wifi_mic_config_samprate_get(void)
{
    return MIC_SAMPRATE;
}

uint16_t wifi_mic_config_tx2rx_air_pkt_size_ms_get(void)
{
    return TX2RX_AIR_PKT_SIZE_MS;
}

uint16_t wifi_mic_config_tx2rx_air_pkt_size_get(void)
{
    return TX2RX_AIR_PKT_SIZE;
}

uint8_t wifi_mic_config_mic_tx_num_get(void)
{
    return MIC_TX_NUM;
}

uint8_t wifi_mic_config_mic_tx_capture_in_ch_num_get(void)
{
    return TX_CAPTURE_IN_CH_NUM;
}

uint8_t wifi_mic_config_mic_tx_capture_out_ch_num_get(void)
{
    return TX_CAPTURE_OUT_CH_NUM;
}

uint8_t wifi_mic_config_mic_tx_playback_ch_num_get(void)
{
    return TX_PLAYBACK_CH_NUM;
}

uint8_t wifi_mic_config_mic_rx_playback_ch_num_get(void)
{
    return RX_PLAYBACK_CH_NUM;
}

uint16_t wifi_mic_config_mic_tx_capture_frame_size_ms_get(void)
{
    return TX_CAPTURE_FRAME_SIZE_MS;
}

uint16_t wifi_mic_config_mic_tx_playback_frame_size_ms_get(void)
{
    return TX_PLAYBACK_FRAME_SIZE_MS;
}

uint16_t wifi_mic_config_mic_rx_playback_frame_size_ms_get(void)
{
    return RX_PLAYBACK_FRAME_SIZE_MS;
}

uint16_t wifi_mic_config_mic_tx_capture_frame_size_get(void)
{
    return TX_CAPTURE_FRAME_SIZE;
}

uint16_t wifi_mic_config_mic_tx_playback_frame_size_get(void)
{
    return TX_PLAYBACK_FRAME_SIZE;
}

uint16_t wifi_mic_config_mic_rx_playback_frame_size_get(void)
{
    return RX_PLAYBACK_FRAME_SIZE;
}

uint16_t wifi_mic_config_mic_tx_capture_ring_buffer_size_ms_get(void)
{
    return TX_CAPTURE_RING_BUFFER_SIZE_MS;
}

uint16_t wifi_mic_config_mic_tx_playback_ring_buffer_size_ms_get(void)
{
    return TX_PLAYBACK_RING_BUFFER_SIZE_MS;
}

uint16_t wifi_mic_config_mic_rx_playback_ring_buffer_size_ms_get(void)
{
    return RX_PLAYBACK_RING_BUFFER_SIZE_MS;
}

uint16_t wifi_mic_config_mic_rx_playback_start_level_size_ms_get(void)
{
    return RX_PLAYBACK_START_LEVEL_SIZE_MS;
}

uint32_t wifi_mic_config_mic_tx_capture_ring_buffer_size_get(void)
{
    return TX_CAPTURE_RING_BUFFER_SIZE;
}

uint32_t wifi_mic_config_mic_tx_playback_ring_buffer_size_get(void)
{
    return TX_PLAYBACK_RING_BUFFER_SIZE;
}

uint32_t wifi_mic_config_mic_rx_playback_ring_buffer_size_get(void)
{
    return RX_PLAYBACK_RING_BUFFER_SIZE;
}

uint32_t wifi_mic_config_mic_rx_playback_start_level_size_get(void)
{
    return RX_PLAYBACK_START_LEVEL_SIZE;
}

uint32_t wifi_mic_config_sta_check_period_ms_get(void)
{
    return STA_CHECK_PERIOD_MS;
}

